### ISSUE TITLE
9th December 2022 Updates

### ISSUE THREAD

**Issue by RussellCollis** [jamf/Jamf-Environment-Test#10]
Can the Jamf IPs as of December 2022 and latest apple IPs be added?

**Comment by daniel-maclaughlin** [comment]
Hi, 
the Jamf IPs listed on https://learn.jamf.com/bundle/technical-articles/page/Permitting_InboundOutbound_Traffic_with_Jamf_Cloud.html are outbound from Jamf Cloud only, this tool is written to test outbound communication from a macOS device.
The latest version 1.6 has updated URLs from Apple's KB article https://support.apple.com/en-us/HT210060
