### ISSUE TITLE
STuck

### ISSUE THREAD

**Issue by zero80472** [jamf/Jamf-Environment-Test#3]
Stuck on Creating the report file when connected to a CISCO VPN (FULL Tunnel) - need to use this to find out what else i need to allow on our fw

**Comment by daniel-maclaughlin** [comment]
Hi, 
can you advise if you're using native MacOS VPN or 3rd party cisco app.

the tasks it could be getting stuck on are part of the initial HTML report would be related to the following so if you can try and run this manually may give an indication of where its getting stuck, you should be able to copy and past each of the below lines into terminal while connected to the VPN and see if each of them completes

sysProfilerNetworkData=$(/usr/sbin/system_profiler SPNetworkDataType 2> /dev/null)
PublicIP=$(/usr/bin/AssetCacheLocatorUtil 2>&1 | /usr/bin/grep "public IP address is" | awk 'NR==1{print $NF}' | /usr/bin/sed 's/\.$//')
LocalIP=$(echo "$sysProfilerNetworkData" | /usr/bin/grep "IPv4 Addresses:" | /usr/bin/awk 'NR==1{print $NF}')
PrimaryNetworkInterface=$( echo "$sysProfilerNetworkData" | /usr/bin/grep -B 5 "IPv4 Addresses:" | /usr/bin/grep "Type: " | /usr/bin/awk 'NR==1{print $NF}')
WIFIInterface=$(networksetup -listallhardwareports | awk '/Hardware Port: Wi-Fi/,/Ethernet/' | awk 'NR==2' | cut -d " " -f 2)

**Comment by zero80472** [comment]
its using Cisco anyconnect VPN and it creates a tunnel interface UTUN2 - i might of fixed it as i got a report just need to verfiy this report on the firewall level but no one from networks is on today ... that has the access
