### ISSUE TITLE
Using  Jamf-Environment-Test behind proxy PAC

### ISSUE THREAD

**Issue by delpech** [jamf/Jamf-Environment-Test#4]
Hello,

my company has opened the range 17.0.0.0/8 on the ports 443 and 5223 (Protocol HTTP / 2) at the Proxy level (Security forbids us any direct opening at the Firewall level).

We an autoproxy PAC. We have tried your script to test the connection to APNs servers but the script only returns information about IPs in 136. *. *. * But nothing about IPs in 17. *. *. *.

Is your application capable of testing the connection behind this type of PROXY? Or do you think something was done wrong with our openings?

Kind regards,
Sylvain

Some results:

HOSTNAME | Reverse DNS | IP Address | Port | Protocol | Accessible | SSL Error
-- | -- | -- | -- | -- | -- | --
gdmf.apple.com |   | 136.173.22.235#53 | 443 | TCP | Unavailable | Not checked
deviceenrollment.apple.com |   | 136.173.22.235#53 | 443 | TCP | Unavailable | Not checked
deviceservices-external.apple.com |   | 136.173.22.235#53 | 443 | TCP | Unavailable | Not checked

APNS apsctl Status | Connected | Apple Push Notifications should be accessible. | If your clients aren't getting Apple push notifications
-- | -- | -- | --

**Comment by daniel-maclaughlin** [comment]
that IP: 136.173.22.235 doesn't appear to belong to Apple at all, I would check on what DNS service is being used in your environment. in terms of using proxy pac the utility does a method of trying to grep of that the PROXY HOST is within the pac url and then uses that with openssl and nc commands so it isn't 100% ereliable depending on the size and structure of the pac
that being said from what you have provided the resolving of the apple urls appears to be intercepted by another service
for exampleif I run nslookup gdmf.apple.com i get a 17.x.x.x address each time
Regards,
Daniel
