### ISSUE TITLE
JET doesn't accurately read PAC file

### ISSUE THREAD

**Issue by brianyaklin** [jamf/Jamf-Environment-Test#6]
We have been testing enterprise Apple connectivity using the JAMF environment test, in an environment with multiple proxies for various business reasons. The proxy is determined based on an auto-proxy configuration script (PAC file). The getProxyAddress() function in "Jamf Environment Test.sh" has the following logic to determine the proxy and port to use (lines 656 through 659 in commit 55661cf):
```
#Get Proxy Host
PROXY_HOST=$(/usr/bin/curl ${AUTO_PROXY_DISCOVERY_URL} | /usr/bin/grep 'PROXY' | /usr/bin/tail -n 1 | /usr/bin/awk '{print $3}' | /usr/bin/tr -d "';" | /usr/bin/cut -d: -f1)
#Get Proxy Port
PROXY_PORT=$(/usr/bin/curl ${AUTO_PROXY_DISCOVERY_URL} | /usr/bin/grep 'PROXY' | /usr/bin/tail -n 1 | /usr/bin/awk '{print $3}' | /usr/bin/tr -d "';" | /usr/bin/cut -d: -f2)
```

What we're seeing is that the JET utility correctly identifies our auto-proxy configuration URL from scutil, but doesn't obtain the correct proxy. All the logic above appears to be doing is greping for the last result of the text PROXY, instead of actually interpreting the JavaScript or executing the FindProxyForURL() function within the PAC file and getting an accurate proxy string returned. Additionally, based on the formatting within our PAC file, these commands don't actually grab the host after the PROXY string because the line that is identified doesn't actually begin with `return "PROXY myproxy.mycompany.com:80"`. The last PROXY text in our PAC file includes an IF statement on a single line with the return, for example:
```
if (shExpMatch(url, "myrandomurl1.com") || shExpMatch(url, "myrandomurl2.com")) { return "PROXY myproxy.mycompany.com:80"; }
```
What is instead being identified as the proxy is the text `myrandomurl1.com`.

As a temporary workaround we have hardcoded our PROXY_HOST and PROXY_URL variables according to our needs for our test host.

**Comment by daniel-maclaughlin** [comment]
The new version will utilise Python pacparser to query the pac file more accurately if 2 proxy servers are provided in the pac file ie PROXY 1.2.3.4:3128; PROXY 5.6.7.8:3128 then JET tool will use the first one. 1.6 currently posted as Beta
