### ISSUE TITLE
JET script improvement for FileVault Status check

### ISSUE THREAD

**Issue by cipineda** [jamf/Jamf-Environment-Test#9]
First of all thanks for this script, it works very good.
I just have an observation, my machine reported not having FileVault enabled, which it does.
Upon checking the code:
`/usr/bin/fdesetup status | /usr/bin/awk '{print $3}' | /usr/bin/tr -d .`
It returned:    
On
keychain

Which are two rows and when compared on line 940 against == "On" it fails.

If you add the 'head' command it should fix it:
`/usr/bin/fdesetup status | /usr/bin/awk '{print $3}' | head -1 | /usr/bin/tr -d .`
Result: `On`

**Comment by daniel-maclaughlin** [comment]
will be added to 1.6.1
